USE faf_dw;

CREATE TABLE IF NOT EXISTS etl_check_log (
  check_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  run_id VARCHAR(36) NOT NULL,
  check_name VARCHAR(255) NOT NULL,
  failed_rows BIGINT NOT NULL,
  status ENUM('PASS','FAIL','INFO','ERROR') NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
